name: Docker Image CI

on:
  push:
    branches: '*'
  pull_request:

env:
  DEFAULT_TAG: "latest"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DEFAULT_TAG: "latest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set Docker Tag
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "DOCKER_TAG=${{ ${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}} }}";
          else
            echo "DOCKER_TAG=${{ env.DEFAULT_TAG }}";
          fi >> $GITHUB_ENV


      - name: Build Builder Image
        run: docker build -t builder:${DOCKER_TAG} -f Dockerfile .

      - name: Build Release Image
        run: docker build -t release:${DOCKER_TAG} -f Dockerfile --target=release .

      - name: Display Docker Images
        run: docker images
